name: tests

on: [push, pull_request]

jobs:
  pest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        testbench: ['^9.0', '^10.0', '^11.0']
        exclude:
          - php: '8.2'
            testbench: '^11.0'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies with testbench ${{ matrix.testbench }}
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: ./vendor/bin/pest
